export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const TRANSACTION_TYPE_LOADED = 'TRANSACTION_TYPE_LOADED';
export const TRANSACTION_TYPE_ERROR = 'TRANSACTION_TYPE_ERROR';
export const TRANSACTION_CATEGORY_LOADED = 'TRANSACTION_CATEGORY_LOADED';
export const TRANSACTION_CATEGORY_ERROR = 'TRANSACTION_CATEGORY_ERROR';
export const TRANSACTION_SUBMIT_SUCCESS = 'TRANSACTION_SUBMIT_SUCCESS';
export const TRANSACTION_SUBMIT_ERROR = 'TRANSACTION_SUBMIT_ERROR';
export const TRANSACTION_SUBMIT_LOADING = 'TRANSACTION_SUBMIT_LOADING';

