export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';
export const GET_TRANSACTIONS_LOADING = 'GET_TRANSACTIONS_LOADING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const TOKEN_EXPIRE = 'TOKEN_EXPIRE';

export const TRANSACTION_TYPE_LOADED = 'TRANSACTION_TYPE_LOADED';
export const TRANSACTION_TYPE_ERROR = 'TRANSACTION_TYPE_ERROR';
export const TRANSACTION_CATEGORY_LOADED = 'TRANSACTION_CATEGORY_LOADED';
export const TRANSACTION_CATEGORY_ERROR = 'TRANSACTION_CATEGORY_ERROR';
export const TRANSACTION_SUBMIT_SUCCESS = 'TRANSACTION_SUBMIT_SUCCESS';
export const TRANSACTION_SUBMIT_ERROR = 'TRANSACTION_SUBMIT_ERROR';
export const TRANSACTION_SUBMIT_LOADING = 'TRANSACTION_SUBMIT_LOADING';
export const TRANSACTION_EDIT_SUCCESS = 'TRANSACTION_EDIT_SUCCESS';
export const TRANSACTION_EDIT_ERROR = 'TRANSACTION_EDIT_ERROR';
export const TRANSACTION_EDIT_LOADING = 'TRANSACTION_EDIT_LOADING';
export const TRANSACTION_NEW_FILE_ERROR = 'TRANSACTION_NEW_FILE_ERROR';
export const OPEN_ADD_MODAL = 'OPEN_ADD_MODAL';
export const OPEN_EDIT_MODAL = 'OPEN_EDIT_MODAL';
export const OPEN_DELETE_MODAL = 'OPEN_DELETE_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const SHOW_INVOICE = 'SHOW_INVOICE';
export const CLOSE_INVOICE = 'CLOSE_INVOICE';
